### ISSUE TITLE
Du nodejs avec du PHP ?

### ISSUE THREAD

**Issue by Ooggle** [Giing/gamerztag#1]
Bonjour,

J'ai très apprécié consulter votre profil et quelle fut ma stupéfaction lorsque je vis une merveilleuse librairie telle que Materialize CSS être utilisée dans un de vos projets. Un homme de culture me suis-je dit.
Cependant, un problème m'a sauté aux yeux en consultant le code. Pourquoi avoir mélangé du nodejs et du PHP ?

J'attends avec impatience votre réponse.
Cordialement

**Comment by charlesboyerCPE** [comment]
Oh mais toi je vais te baffer

**Comment by Giing** [comment]
Bonjour Monsieur,

J'ai bien pris note de votre remarque et je comprends bien la confusion que
cela peut représenter.
En effet, il n'est pas habituel de voir deux langages de programmation côté
serveur fonctionner en si belle harmonie.
Tout cela s'explique par la phrase suivant : "Tout seul on va plus vite;
ensemble, on va plus loin".

Je vous prie, monsieur, d'agréer l'expression de mes sentiments distingués.
Bien à vous

Le lun. 2 nov. 2020 à 20:38, charles.boyer <notifications@github.com> a
écrit :

**Comment by Ooggle** [comment]
Bonjour,

Je prends en compte votre point de vue.
Bien que divergeant du mien, je n'ai pu qu'être charmé par la somptueuse forme avec laquelle vous avez formulé votre argumentaire.

Je clore cette issue, mais pas notre amitié naissante.

Au plaisir de rediscuter avez vous,
Bien cordialement
